services:
    cobalt-api:
        image: ghcr.io/br0k3x/cobalt:staging-api

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt-api

        ports:
            - 9000:9000/tcp
            # if you use a reverse proxy (such as nginx),
            # uncomment the next line and remove the one above (9000:9000/tcp):
            # - 127.0.0.1:9010:9010

        environment:
            # replace https://api.url.example/ with your instance's url
            # or else tunneling functionality won't work properly
            API_URL: "https://api.url.example/"

            # if you want to use cookies for fetching data from services,
            # uncomment the next line & volumes section
            # COOKIE_PATH: "/cookies.json"

            # it's recommended to configure bot protection or api keys if the instance is public,
            # see /docs/protect-an-instance.md for more info

            # see /docs/run-an-instance.md for more variables that you can use here

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt
        # uncomment only if you use the COOKIE_PATH variable
        # volumes:
            # - ./cookies.json:/cookies.json
    cobalt-web:
        image: ghcr.io/br0k3x/cobalt:staging-web
        restart: unless-stopped
        container_name: cobalt-web
        ports:
            - 3000:3000/tcp
        environment:
            # replace https://cobalt.url.example/ with your instance's url
            WEB_HOST: "https://cobalt.url.example/"
        depends_on: 
            - cobalt-api
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt
    # watchtower updates the cobalt image automatically
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # if needed, use this image for automatically generating poToken & visitor_data
    # yt-session-generator:
    #     image: ghcr.io/imputnet/yt-session-generator:webserver

    #     init: true
    #     restart: unless-stopped
    #     container_name: yt-session-generator
    #     labels:
    #       - com.centurylinklabs.watchtower.scope=cobalt
